services:
  backend:
    image: tankaus/backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    image: tankaus/frontend:latest
    ports:
      - "80:80"
    container_name: "FRONTEND"
    depends_on:
      - backend

  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    depends_on:
      - database
