services:
  backend:
    image: tankaus/backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    image: tankaus/frontend:latest
    ports:
      - "80:80"
    container_name: "FRONTEND"
    depends_on:
      - backend

  database:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"

